name: Python Unittest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install MyApp
        run: |
          python -m pip install --upgrade pip
          pip install ./app
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run Tests
        run: python -m unittest discover app/tests